sudo: required

language: rust

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

services:
  - docker

before_script:
  - docker-compose build
  - docker-compose run chaos bash -c "cd /tmp; rustup component add rust-src"
  - docker-compose run chaos bash -c "cd /tmp; bootimage build"

script:
  - docker-compose run chaos bash -c "cd /tmp; bootimage build"
  - docker-compose run chaos bash -c "cd /tmp; cargo test"
  - docker-compose run chaos bash -c "cd /tmp; bootimage test"

